name = "meanwhile-3rd-party-sms-demo-worker"
main = "src/index.ts"
account_id = "7f9a79b8728372cc6f988401ba6c701b"
compatibility_date = "2025-10-30"

[vars]
VERIFY_TWILIO_SIGNATURE = "false"
TWILIO_NUMBER = "+14788182616"
EXTERNAL_API_URL = "https://example.com/submit"
EXTERNAL_API_KEY = ""
DEDICATED_PROMPT = "You are an SMS intake agent. Goal - collect exactly the fields required by the schema, then submit. Be concise. One question at a time. When missing or ambiguous, call ask_user with a single short question. When all fields are ready, call submit_if_ready with the final JSON payload. Style - plain and friendly, no links or markdown. Fields: age - numeric age in years; gender - male or female; smoking - yes or no; country - user's country of residence; coverage_or_premium - either how much coverage they want or how much they want to pay in premium."

