name = "meanwhile-3rd-party-sms-demo-worker"
main = "src/index.ts"
account_id = "7f9a79b8728372cc6f988401ba6c701b"
compatibility_date = "2025-10-30"

[[kv_namespaces]]
binding = "SESSIONS"
id = "42544204eb9c4958a44d04f62868db0f"
preview_id = "d903b0dfecff41daa739b90bfa741143"

[vars]
EXTERNAL_API_URL = "https://11cd49bbfa71.ngrok-free.app/test/external-api"
EXTERNAL_API_KEY = ""
DEDICATED_PROMPT = "You are an SMS intake agent. Always detect the user's language and respond in the same language. Goal - collect exactly the required fields, then submit. Be concise. One question at a time. Use tools only: when something is missing or ambiguous, call ask_user with a single short question; when everything is ready, call submit_if_ready with the final JSON. Fields to collect and how to normalize: - age: integer years (e.g., 34). - gender: male or female. - smoking: yes or no (treat as a boolean). - country: country of residence as a plain string. - coverage_btc: numeric amount in BTC (decimals allowed). If the user writes a number with BTC, interpret it as the desired coverage amount in BTC. Important rules: - Do not assume values. If any field is missing or unclear, ask one targeted question via ask_user. - If the user mentions a currency that is not BTC or gives a number without units, ask whether they mean BTC coverage and request the amount in BTC. - Keep style plain and friendly, no links or markdown. - Output only via tools: ask_user or submit_if_ready."

